### ISSUE TITLE
 mapchete pyramid <raster_file> error

### ISSUE THREAD

**Issue by giswt** [ungarj/mapchete#118]
I  install  mapchete  using this command pip install mapchete   (ubuntu 16.04     python 2.7)
when run   mapchete pyramid Honghe.tif  /home/wt 
get the error 
Traceback (most recent call last):
  File "/usr/local/bin/mapchete", line 11, in <module>
    load_entry_point('mapchete==0.22', 'console_scripts', 'mapchete')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/mapchete/__init__.py", line 3, in <module>
    from mapchete._core import open, count_tiles, Mapchete, MapcheteProcess
  File "/usr/local/lib/python2.7/dist-packages/mapchete/_core.py", line 17, in <module>
    from tilematrix import TilePyramid
  File "/usr/local/lib/python2.7/dist-packages/tilematrix/__init__.py", line 3, in <module>
    from ._tilepyramid import TilePyramid
  File "/usr/local/lib/python2.7/dist-packages/tilematrix/_tilepyramid.py", line 6, in <module>
    from . import _funcs
  File "/usr/local/lib/python2.7/dist-packages/tilematrix/_funcs.py", line 5, in <module>
    from rasterio.crs import CRS
  File "/usr/local/lib/python2.7/dist-packages/rasterio/__init__.py", line 23, in <module>
    from rasterio._base import gdal_version
  File "rasterio/_base.pyx", line 27, in init rasterio._base
  File "/usr/local/lib/python2.7/dist-packages/rasterio/env.py", line 16, in <module>
    from rasterio.path import parse_path
  File "/usr/local/lib/python2.7/dist-packages/rasterio/path.py", line 33, in <module>
    @attr.s(slots=True)
TypeError: attributes() got an unexpected keyword argument 'slots'

I want to use this tool to generate tiles like the 
 https://github.com/ungarj/mapchete_testdata/tree/master/tiled_data/raster/cleantopo/1

**Comment by giswt** [comment]
I think there is something  wrong with my environment.
thanks.
