### ISSUE TITLE
process stalls when using rasterio>1.0.13

### ISSUE THREAD

**Issue by ungarj** [ungarj/mapchete#155]
rasterio's `_CRS` class has been refactured and seems to cause process stall whenever using multiprocessing.

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 241, in _feed
    obj = ForkingPickler.dumps(obj)
  File "/usr/lib/python3.5/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
  File "stringsource", line 2, in rasterio._crs._CRS.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
```

**Comment by ungarj** [comment]
will be closed with https://github.com/mapbox/rasterio/issues/1625
